#Insurance Data Preprocessing

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

Mounted at /content/drive

## Columns in Data

X.1 Internal identification number assigned to each annual contract formal-
ized by an insured.

X.2 Start date of the policyholder’s contract (DD/MM/YYYY).

X.3 Date of last contract renewal (DD/MM/YYYY).

X.4 Date of the next contract renewal (DD/MM/YYYY).

X.5 Date of birth of the insured declared in the policy (DD/MM/YYYY).

X.6 Date of issuance of the insured person’s driver’s license
(DD/MM/YYYY).

X.7 Channel through which the policy was contracted (0: Agent, 1: Insur-
ance brokers).

X.8 Total number of years that the insured has been associated with the
insurance entity.

X.9 Total number of policies held by the insured in the insurance entity.

X.10 Maximum number of policies that the insured has ever had in force.

X.11 Maximum number of products that the insured has simultaneously held
at any given point.

X.12 Number of policies canceled or terminated for nonpayment in the current
year.

X.13 Last payment method of the reference policy (1: half-yearly, 0: annual).

X.14 Net premium amount associated with the policy during the current year.

X.15 Total cost of claims for the insurance policy during the current year.

X.16 Total number of claims incurred for the insurance policy during the
current year.

X.17 Total number of claims filed throughout the entire duration of the policy.

X.18 Ratio of the number of claims filed to the total duration (years) of the
policy in force.

X.19 Type of risk (1: motorbikes, 2: vans, 3: passenger cars, 4: agricultural
vehicles).

X.20 0 for rural, 1 for urban (more than 30,000 inhabitants).

X.21 1 if multiple regular drivers are declared, 0 if only one driver is declared.

X.22 Year of vehicle registration (YYYY).

X.23 Vehicle power measured in horsepower.

X.24 Cylinder capacity of the vehicle.

X.25 Market value of the vehicle as of 31/12/2019.

X.26 Number of vehicle doors.

X.27 Energy source used to power the vehicle (P: Petrol, D: Diesel).

X.28 Vehicle weight in kilograms.

In [ ]:
# Replace the path the actual folder name
os.chdir('/content/drive/MyDrive/530 Project/data')

In [ ]:
insurance_pre_train = pd.read_csv('insurance_train.csv')

In [ ]:
insurance_pre_train.sample(5)

,X.1,X.2,X.3,X.4,X.5,X.6,X.7,X.8,X.9,X.10,...,X.19,X.20,X.21,X.22,X.23,X.24,X.25,X.26,X.27,X.28
521,8160,15/05/2012,15/05/2018,15/05/2019,01/06/1967,15/07/1985,0,10,1,2,...,3,0,0,2011,105,1598,15338.3,5,P,1094
34627,9474,10/06/2014,10/06/2016,10/06/2017,28/11/1990,24/02/2010,1,3,1,1,...,3,0,0,2011,85,1390,14750.0,3,P,995
24102,18300,27/12/2016,27/12/2016,27/12/2017,18/06/1964,01/01/1984,1,3,5,5,...,3,0,0,2012,150,2997,69800.0,2,D,1500
14992,28097,09/06/2014,09/06/2018,09/06/2019,19/02/1975,01/03/1993,0,4,1,2,...,3,1,0,2002,123,1783,22200.0,5,P,1315
27581,28179,05/05/2017,05/05/2018,05/05/2019,14/04/1979,14/06/1998,0,2,1,1,...,1,0,0,2013,4,49,1535.0,0,P,78

In [ ]:
insurance_pre_train.shape

(37451, 28)

In [ ]:
insurance_pre_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37451 entries, 0 to 37450
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X.1     37451 non-null  int64
 1   X.2     37451 non-null  object
 2   X.3     37451 non-null  object
 3   X.4     37451 non-null  object
 4   X.5     37451 non-null  object
 5   X.6     37451 non-null  object
 6   X.7     37451 non-null  int64
 7   X.8     37451 non-null  int64
 8   X.9     37451 non-null  int64
 9   X.10    37451 non-null  int64
 10  X.11    37451 non-null  int64
 11  X.12    37451 non-null  int64
 12  X.13    37451 non-null  int64
 13  X.14    37451 non-null  float64
 14  X.15    37451 non-null  float64
 15  X.16    37451 non-null  int64
 16  X.17    37451 non-null  int64
 17  X.18    37451 non-null  float64
 18  X.19    37451 non-null  int64
 19  X.20    37451 non-null  int64
 20  X.21    37451 non-null  int64
 21  X.22    37451 non-null  int64
 22  X.23    37451 non-null  int64
 23  X.24    37451 non-null  int64
 24  X.25    37451 non-null  float64
 25  X.26    37451 non-null  int64
 26  X.27    36858 non-null  object
 27  X.28    37451 non-null  int64
dtypes: float64(4), int64(18), object(6)
memory usage: 8.0+ MB

In [ ]:
insurance_pre_train['X.27'].value_counts()

X.27
D    23074
P    13784
Name: count, dtype: int64

In [ ]:
insurance_pre_train['LC'] = insurance_pre_train['X.15'] / insurance_pre_train['X.16']
insurance_pre_train['LC'] = insurance_pre_train['LC'].fillna(0)
insurance_pre_train['HALC'] = insurance_pre_train['LC'] * insurance_pre_train['X.18']

insurance_pre_train['CS'] = (insurance_pre_train['X.16'] > 0).astype(int)

In [ ]:
insurance_pre_train['X.27'] = insurance_pre_train['X.27'].fillna(insurance_pre_train['X.27'].mode())

In [ ]:
insurance_pre_train['X.27'].value_counts()

X.27
D    23074
P    13784
Name: count, dtype: int64

In [ ]:
insurance_pre_train.drop(columns=['X.1','X.15', 'X.16','X.18', 'X.17'], inplace=True)

In [ ]:
insurance_pre_train.columns

Index(['X.2', 'X.3', 'X.4', 'X.5', 'X.6', 'X.7', 'X.8', 'X.9', 'X.10', 'X.11',
       'X.12', 'X.13', 'X.14', 'X.19', 'X.20', 'X.21', 'X.22', 'X.23', 'X.24',
       'X.25', 'X.26', 'X.27', 'X.28', 'LC', 'HALC', 'CS'],
      dtype='object')

In [ ]:
# Make necessary date columns
date_cols = ['X.2','X.3','X.4','X.5','X.6']

# Convert them all to datetime, specifying dayfirst for DD/MM/YYYY
for c in date_cols:
    insurance_pre_train[c] = pd.to_datetime(
        insurance_pre_train[c],
        dayfirst=True,
        errors='coerce'
    )

# Now you can safely compute differences:
insurance_pre_train['policy_duration_days'] = (
    insurance_pre_train['X.4'] - insurance_pre_train['X.2']
).dt.days

insurance_pre_train['time_since_last_renewal_days'] = (
    insurance_pre_train['X.3'] - insurance_pre_train['X.2']
).dt.days

insurance_pre_train['insured_age_years'] = (
    insurance_pre_train['X.2'] - insurance_pre_train['X.5']
).dt.days / 365.25

insurance_pre_train['license_age_years'] = (
    insurance_pre_train['X.2'] - insurance_pre_train['X.6']
).dt.days / 365.25

# Quick check
print(insurance_pre_train[[
    *date_cols,
    'policy_duration_days',
    'time_since_last_renewal_days',
    'insured_age_years',
    'license_age_years'
]].head())

         X.2        X.3        X.4        X.5        X.6  \
0 2017-06-01 2017-06-01 2018-06-01 1996-08-29 2016-05-31
1 2016-09-19 2018-09-19 2019-09-19 1992-04-30 2010-08-03
2 2003-01-08 2018-01-08 2019-01-08 1972-03-23 1998-02-01
3 2015-10-01 2018-10-01 2019-10-01 1946-03-05 1964-08-07
4 2017-01-26 2018-01-26 2019-01-26 1973-04-25 1998-07-24

   policy_duration_days  time_since_last_renewal_days  insured_age_years  \
0                   365                             0          20.755647
1                  1095                           730          24.388775
2                  5844                          5479          30.795346
3                  1461                          1096          69.574264
4                   730                           365          43.756331

   license_age_years
0           1.002053
1           6.130048
2           4.933607
3          51.148528
4          18.510609

In [ ]:
insurance_pre_train.drop(columns=['X.2','X.3','X.4','X.5','X.6'], inplace=True)

In [ ]:
insurance_pre_train.head()

,X.7,X.8,X.9,X.10,X.11,X.12,X.13,X.14,X.19,X.20,...,X.26,X.27,X.28,LC,HALC,CS,policy_duration_days,time_since_last_renewal_days,insured_age_years,license_age_years
0,0,1,1,1,1,1,0,573.07,3,0,...,4,P,1040,0.0,0.0,0,365,0,20.755647,1.002053
1,0,3,1,1,1,0,0,299.19,3,0,...,5,D,1165,0.0,0.0,0,1095,730,24.388775,6.130048
2,1,20,2,2,1,0,0,257.66,3,0,...,5,P,1235,0.0,0.0,0,5844,5479,30.795346,4.933607
3,0,8,2,3,1,0,0,288.70,3,0,...,5,D,1984,0.0,0.0,0,1461,1096,69.574264,51.148528
4,0,9,1,1,1,0,0,741.16,3,0,...,3,P,1702,0.0,0.0,0,730,365,43.756331,18.510609

In [ ]:
insurance_pre_train.isna().sum()

X.7                               0
X.8                               0
X.9                               0
X.10                              0
X.11                              0
X.12                              0
X.13                              0
X.14                              0
X.19                              0
X.20                              0
X.21                              0
X.22                              0
X.23                              0
X.24                              0
X.25                              0
X.26                              0
X.27                            593
X.28                              0
LC                                0
HALC                              0
CS                                0
policy_duration_days              0
time_since_last_renewal_days      0
insured_age_years                 0
license_age_years                 0
dtype: int64

In [ ]:
# Power-to-Weight Ratio (avoid div by 0)
insurance_pre_train['power_to_weight'] = (
    insurance_pre_train['X.23'] / insurance_pre_train['X.28'].replace(0, np.nan)
)

# Engine Size per Door
insurance_pre_train['engine_per_door'] = (
    insurance_pre_train['X.24'] / insurance_pre_train['X.26'].replace(0, np.nan)
)

# Premium-to-Market Value Ratio
insurance_pre_train['premium_to_value'] = (
    insurance_pre_train['X.14'] / insurance_pre_train['X.25'].replace(0, np.nan)
)

In [ ]:
# Policy Density
insurance_pre_train['policy_density'] = (
    insurance_pre_train['X.9'] / insurance_pre_train['X.8'].replace(0, np.nan)
)

# Policy Change Ratio
insurance_pre_train['policy_change_ratio'] = (
    insurance_pre_train['X.10'] / insurance_pre_train['X.9'].replace(0, np.nan)
)

# Product Penetration
insurance_pre_train['product_penetration'] = (
    insurance_pre_train['X.11'] / insurance_pre_train['X.9'].replace(0, np.nan)
)

# Cancellation Rate
insurance_pre_train['cancellation_rate'] = (
    insurance_pre_train['X.12'] / insurance_pre_train['X.8'].replace(0, np.nan)
)

In [ ]:
insurance_pre_train.isna().sum()

X.7                                0
X.8                                0
X.9                                0
X.10                               0
X.11                               0
X.12                               0
X.13                               0
X.14                               0
X.19                               0
X.20                               0
X.21                               0
X.22                               0
X.23                               0
X.24                               0
X.25                               0
X.26                               0
X.27                             593
X.28                               0
LC                                 0
HALC                               0
CS                                 0
policy_duration_days               0
time_since_last_renewal_days       0
insured_age_years                  0
license_age_years                  0
power_to_weight                    0
engine_per_door                 3259
premium_to_value                   0
policy_density                     0
policy_change_ratio                0
product_penetration                0
cancellation_rate                  0
dtype: int64

In [ ]:
insurance_pre_train.fillna(0, inplace=True)

In [ ]:
insurance_pre_train

,X.7,X.8,X.9,X.10,X.11,X.12,X.13,X.14,X.19,X.20,...,time_since_last_renewal_days,insured_age_years,license_age_years,power_to_weight,engine_per_door,premium_to_value,policy_density,policy_change_ratio,product_penetration,cancellation_rate
0,0,1,1,1,1,1,0,573.07,3,0,...,0,20.755647,1.002053,0.072115,340.000000,0.044787,1.000000,1.0,1.0,1.0
1,0,3,1,1,1,0,0,299.19,3,0,...,730,24.388775,6.130048,0.085837,379.200000,0.019446,0.333333,1.0,1.0,0.0
2,1,20,2,2,1,0,0,257.66,3,0,...,5479,30.795346,4.933607,0.076923,278.000000,0.015644,0.100000,1.0,0.5,0.0
3,0,8,2,3,1,0,0,288.70,3,0,...,1096,69.574264,51.148528,0.070565,499.400000,0.010544,0.250000,1.5,0.5,0.0
4,0,9,1,1,1,0,0,741.16,3,0,...,365,43.756331,18.510609,0.047004,656.333333,0.020250,0.111111,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37446,1,1,1,1,1,0,0,402.66,2,0,...,0,57.730322,37.645448,0.047863,379.200000,0.016793,1.000000,1.0,1.0,0.0
37447,0,18,1,1,1,0,0,84.43,4,0,...,6209,56.640657,38.143737,0.017901,0.000000,0.001967,0.055556,1.0,1.0,0.0
37448,0,3,1,1,1,0,0,254.92,3,1,...,731,23.794661,4.744695,0.070064,332.666667,0.030253,0.333333,1.0,1.0,0.0
37449,0,2,1,1,1,1,0,89.38,1,0,...,365,40.427105,19.608487,0.085714,0.000000,0.041284,0.500000,1.0,1.0,0.5
37450,1,2,1,1,1,0,0,383.02,3,1,...,365,63.482546,37.371663,0.084034,199.800000,0.021849,0.500000,1.0,1.0,0.0

In [ ]:
insurance_pre_train['vehicle_age'] = 2022 - insurance_pre_train['X.22']
insurance_pre_train['vehicle_age']

0        28
1        18
2        20
3        12
4        24
         ..
37446    14
37447    21
37448    26
37449    17
37450     5
Name: vehicle_age, Length: 37451, dtype: int64

In [ ]:
insurance_pre_train.drop(columns=['X.22'], inplace=True)

In [ ]:
insurance_pre_train['X.27']

0        P
1        D
2        P
3        D
4        P
        ..
37446    D
37447    D
37448    P
37449    P
37450    P
Name: X.27, Length: 37451, dtype: object

In [ ]:
insurance_pre_train['X.27'] = insurance_pre_train['X.27'].map({'P': 0, 'D': 1})

In [ ]:
pd.set_option("display.max_columns", None)
insurance_pre_train

,X.7,X.8,X.9,X.10,X.11,X.12,X.13,X.14,X.19,X.20,X.21,X.23,X.24,X.25,X.26,X.27,X.28,LC,HALC,CS,policy_duration_days,time_since_last_renewal_days,insured_age_years,license_age_years,power_to_weight,engine_per_door,premium_to_value,policy_density,policy_change_ratio,product_penetration,cancellation_rate,vehicle_age
0,0,1,1,1,1,1,0,573.07,3,0,0,75,1360,12795.55,4,0.0,1040,0.0,0.0,0,365,0,20.755647,1.002053,0.072115,340.000000,0.044787,1.000000,1.0,1.0,1.0,28
1,0,3,1,1,1,0,0,299.19,3,0,0,100,1896,15386.00,5,1.0,1165,0.0,0.0,0,1095,730,24.388775,6.130048,0.085837,379.200000,0.019446,0.333333,1.0,1.0,0.0,18
2,1,20,2,2,1,0,0,257.66,3,0,0,95,1390,16470.00,5,0.0,1235,0.0,0.0,0,5844,5479,30.795346,4.933607,0.076923,278.000000,0.015644,0.100000,1.0,0.5,0.0,20
3,0,8,2,3,1,0,0,288.70,3,0,0,140,2497,27381.00,5,1.0,1984,0.0,0.0,0,1461,1096,69.574264,51.148528,0.070565,499.400000,0.010544,0.250000,1.5,0.5,0.0,12
4,0,9,1,1,1,0,0,741.16,3,0,0,80,1969,36600.00,3,0.0,1702,0.0,0.0,0,730,365,43.756331,18.510609,0.047004,656.333333,0.020250,0.111111,1.0,1.0,0.0,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37446,1,1,1,1,1,0,0,402.66,2,0,0,84,1896,23977.20,5,1.0,1755,0.0,0.0,0,365,0,57.730322,37.645448,0.047863,379.200000,0.016793,1.000000,1.0,1.0,0.0,14
37447,0,18,1,1,1,0,0,84.43,4,0,0,81,4525,42920.00,0,1.0,4525,0.0,0.0,0,6574,6209,56.640657,38.143737,0.017901,0.000000,0.001967,0.055556,1.0,1.0,0.0,21
37448,0,3,1,1,1,0,0,254.92,3,1,0,55,998,8426.19,3,0.0,785,0.0,0.0,0,1096,731,23.794661,4.744695,0.070064,332.666667,0.030253,0.333333,1.0,1.0,0.0,26
37449,0,2,1,1,1,1,0,89.38,1,0,0,9,125,2165.00,0,0.0,105,0.0,0.0,0,730,365,40.427105,19.608487,0.085714,0.000000,0.041284,0.500000,1.0,1.0,0.5,17
37450,1,2,1,1,1,0,0,383.02,3,1,0,100,999,17530.00,5,0.0,1190,0.0,0.0,0,730,365,63.482546,37.371663,0.084034,199.800000,0.021849,0.500000,1.0,1.0,0.0,5

In [ ]:
insurance_pre_train.CS.value_counts()

CS
0    33300
1     4151
Name: count, dtype: int64

In [ ]:
insurance_pre_train.to_csv('insurance_pre_train.csv')

In [ ]:
LC_train = insurance_pre_train.drop(columns='HALC').copy()

In [ ]:
LC_train.sample(5)

,X.7,X.8,X.9,X.10,X.11,X.12,X.13,X.14,X.19,X.20,X.21,X.23,X.24,X.25,X.26,X.27,X.28,LC,CS,policy_duration_days,time_since_last_renewal_days,insured_age_years,license_age_years,power_to_weight,engine_per_door,premium_to_value,policy_density,policy_change_ratio,product_penetration,cancellation_rate,vehicle_age
7545,1,2,1,1,1,1,1,273.10,3,0,0,60,1390,9824.51,5,0.0,1020,0.00,0,731,366,38.212183,8.068446,0.058824,278.000000,0.027798,0.500000,1.0,1.000000,0.5,21
30688,0,21,4,4,1,0,1,282.32,3,0,0,110,1390,21890.00,5,0.0,1260,0.00,0,730,365,52.911704,34.217659,0.087302,278.000000,0.012897,0.190476,1.0,0.250000,0.0,19
3294,0,2,1,1,1,1,1,335.30,3,1,0,113,1590,14724.80,5,0.0,1235,35191.03,1,731,366,32.186174,10.579055,0.091498,318.000000,0.022771,0.500000,1.0,1.000000,0.5,26
24233,0,1,1,1,1,0,1,274.37,3,0,0,87,1948,18348.00,5,1.0,1965,62.22,1,365,0,48.517454,28.963723,0.044275,389.600000,0.014954,1.000000,1.0,1.000000,0.0,21
31727,0,4,3,3,1,0,0,249.49,3,0,0,100,2663,22513.91,3,1.0,1730,0.00,0,1461,1096,47.726215,29.675565,0.057803,887.666667,0.011082,0.750000,1.0,0.333333,0.0,23

In [ ]:
HALC_train = insurance_pre_train.drop(columns='LC').copy()

In [ ]:
HALC_train.sample(5)

,X.7,X.8,X.9,X.10,X.11,X.12,X.13,X.14,X.19,X.20,X.21,X.23,X.24,X.25,X.26,X.27,X.28,HALC,policy_duration_days,time_since_last_renewal_days,insured_age_years,license_age_years,power_to_weight,engine_per_door,premium_to_value,policy_density,policy_change_ratio,product_penetration,cancellation_rate,vehicle_age
27915,1,6,1,2,1,0,0,342.20,2,0,1,75,1560,20449.98,4,1,1292,0.0000,1095,730,39.975359,20.889802,0.058050,390.0,0.016734,0.166667,2.0,1.0,0.000000,11
30594,0,5,1,2,1,1,0,463.57,3,1,0,70,1398,15635.00,5,1,1022,0.0000,1827,1461,23.780972,4.605065,0.068493,279.6,0.029650,0.200000,2.0,1.0,0.200000,10
26669,1,3,2,2,1,1,1,389.99,3,1,1,82,1995,16894.45,5,1,1430,0.0000,1095,730,45.530459,9.607118,0.057343,399.0,0.023084,0.666667,1.0,0.5,0.333333,23
2313,1,3,2,2,1,0,1,334.49,3,0,1,90,1598,16540.00,5,1,1120,710.1996,365,0,33.292266,15.167693,0.080357,319.6,0.020223,0.666667,1.0,0.5,0.000000,13
22740,0,10,1,5,2,1,1,323.40,3,0,0,154,1985,24611.45,5,0,1450,0.0000,1461,1096,68.848734,48.602327,0.106207,397.0,0.013140,0.100000,5.0,2.0,0.100000,21

In [ ]:
LC_train.to_csv('LC_train.csv')

In [ ]:
HALC_train.to_csv('HALC_train.csv')